name: Cache-Clean

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto_clean:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache Clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete --all
